### ISSUE TITLE
No datasets in the repository

### ISSUE THREAD

**Issue by ghost** [amueller/mglearn#1]
Hi
There is no datasets in the repository and all datasets called in the packages seems local to your OS.

**Comment by amueller** [comment]
I added the bike and ram datasets to the repo with the notebooks:
https://github.com/amueller/introduction_to_ml_with_python
Do you still have problems with them?

**Comment by amueller** [comment]
Ah, I guess I should add them here too, though that wasn't really the plan... maybe I shouldn't have made this repo in the first place... hum....

**Comment by ghost** [comment]
I have no idea which decision is the best one, but mglearn notebooks cannot be properly used by users without its datasets.

In 4th and 6th chapters we need datasets which are not public  in your repo yet.

BTW, mglearn is excellent work. Thanks for sharing it.

⁣Best Regard,
Behrooz​

**Comment by amueller** [comment]
which datasets are not included yet?

**Comment by ghost** [comment]
all the data you used in chapter 4 and chapter 6 of your notebooks here https://github.com/amueller/introduction_to_ml_with_python

**Comment by amueller** [comment]
oh damn, I made a mistake when pushing the ram prices and citibike. give me a second.

**Comment by amueller** [comment]
ram prices and citibike are there now.

**Comment by amueller** [comment]
and adult now, too

**Comment by amueller** [comment]
anything else missing?

**Comment by ghost** [comment]
yes, some of datasets you used is on your local machine, for example:
reviews_train = load_files("data/aclImdb/train/")
here : https://github.com/amueller/introduction_to_ml_with_python/blob/master/07-working-with-text-data.ipynb

**Comment by amueller** [comment]
clearly not "all datasets" because I just told you that I fixed the three ones mentioned above. Unfortunately my processing of the notebook ate the instructions on how to download this dataset. It's quite big and I can't add it to the repository. I'll add a note into the readme on how to download it.

**Comment by amueller** [comment]
ok, added the link to the readme. Any more?

**Comment by ghost** [comment]
Not yet, but will be updated chapter by chapter.

**Comment by ghost** [comment]
Thanks a lot for your kindness and attention

**Comment by amueller** [comment]
should be good now.
