### ISSUE TITLE
ModuleNotFoundError: No module named 'mglearn'

### ISSUE THREAD

**Issue by FrancescoZangaro** [amueller/mglearn#13]
I have already installed the mglearn package through the comand pip install mglearn in Anaconda Prompt. The installation was successful because I see the folders mglearn and mglearn-0.1.7.dist-info inside site-packages, and when I run the comand pip install mglearn in the Anaconda Prompt, I receive the following message:
Requirement already satisfied: mglearn in c:\users\cesco\anaconda3\lib\site-packages (0.1.7)
.... (some other stuff)
However, I receive the following error from Spyder:
 import mglearn
ModuleNotFoundError: No module named 'mglearn'

I have already tried to restart the computer and the program.
I am using Spyder, just in case this might be important.
Any hint on where the problem might be?
Thank you for your help

**Comment by amueller** [comment]
Spyder probably uses a different python environment than the environment you installed into. I'm not familiar with choosing the environment for Spyder as I don't use spyder.
You might find https://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/ helpful, though it deals with jupyter, not spyder.

**Comment by mingmingi** [comment]
I have problem as previous question.
but I use Jupyter.

![image](https://user-images.githubusercontent.com/52272405/60242002-9a9b8580-98ef-11e9-82c7-60ab53710703.png)

import mglearn
ModuleNotFoundError: No module named 'mglearn'
What can i do ?

**Comment by amueller** [comment]
@mingmingi you have to install it.
The easiest way is to run
```
!pip install mglearn
```
in jupyter.
If that doesn't work, check out
https://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/
