### ISSUE TITLE
DeprecationWarning: Function make_blobs is deprecated; Please import make_blobs directly from scikit-learn   warnings.warn(msg, category=DeprecationWarning)

### ISSUE THREAD

**Issue by nicolasplanchon** [amueller/mglearn#14]
Hi there,
This issue will be very easy to understand

![image](https://user-images.githubusercontent.com/33055289/49161521-4ca6ab00-f329-11e8-83ca-ac083591aac3.png)

**Comment by amueller** [comment]
I'm not sure what you are asking. I'm saying that I'm going to be removing this function as it went upstream to sklearn with a slightly different interface. There is no use of this in the book / the notebooks any more.

**Comment by nicolasplanchon** [comment]
page 40 in the chapter regarding the knn classifier you use it, and it doesn't work that way.

**Comment by amueller** [comment]
It totally still works. And yes, obviously old printed books still use it because paper doesn't update. Newer prints don't use it.
This is just a warning and doesn't change anything.

**Comment by greennomad424242** [comment]
Hi. This warning is still present when using code in the Kindle-based version (as of February 2019).

**Comment by amueller** [comment]
@greennomad424242 what's the code there?

**Comment by sanghee1021** [comment]
wow. i had the same issue, but it didn't seem to affect anything but creating a warning sign.
