### ISSUE TITLE
import mglearn in MacOS for Python 3 (3.7) error

### ISSUE THREAD

**Issue by staronline1and2** [amueller/mglearn#15]
**Hello,**

**My apologies if this issue is already solved but I tried looking around and I trying to figures out how to install mglearn in Python 3 rather than Python 2 on my MacOS.**

>>> import mglearn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mglearn/__init__.py", line 1, in <module>
    from . import plots
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mglearn/plots.py", line 14, in <module>
    from .plot_pca import plot_pca_illustration, plot_pca_whitening, plot_pca_faces
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mglearn/plot_pca.py", line 7, in <module>
    memory = Memory(cachedir="cache")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/externals/joblib/memory.py", line 897, in __init__
    **backend_options))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/externals/joblib/memory.py", line 125, in _store_backend_factory
    backend_options=backend_options)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/externals/joblib/_store_backends.py", line 401, in configure
    mkdirp(self.location)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/externals/joblib/disk.py", line 60, in mkdirp
    os.makedirs(d)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 1] Operation not permitted: 'cache'

**I got an PermissionError according to my error message.**

UserMBP:bin user$ pip3 install mglearn
Requirement already satisfied: mglearn in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (0.1.7)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from mglearn) (1.16.2)
Requirement already satisfied: matplotlib in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from mglearn) (3.0.3)
Requirement already satisfied: scikit-learn in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from mglearn) (0.20.3)
Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from mglearn) (0.24.2)
Requirement already satisfied: pillow in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from mglearn) (6.0.0)
Requirement already satisfied: cycler in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from mglearn) (0.10.0)
Requirement already satisfied: imageio in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from mglearn) (2.5.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from matplotlib->mglearn) (1.0.1)
Requirement already satisfied: python-dateutil>=2.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from matplotlib->mglearn) (2.8.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from matplotlib->mglearn) (2.4.0)
Requirement already satisfied: scipy>=0.13.3 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from scikit-learn->mglearn) (1.2.1)
Requirement already satisfied: pytz>=2011k in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pandas->mglearn) (2019.1)
Requirement already satisfied: six in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from cycler->mglearn) (1.12.0)
Requirement already satisfied: setuptools in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib->mglearn) (40.8.0)

**As you can see mglearn is already installed.**

**Thanks,**

**staronline1and2**

**Comment by amueller** [comment]
This looks like you're trying to execute a script in a folder that you don't have permission to write. The code tries to create a cache directory but it's not permitted.

**Comment by staronline1and2** [comment]
Hello amueller,

Thank you for the tip because I would not have figured it out as a cache directory permission error. The solution was that I uninstalled the mglearn and restarted my computer. I installed mglearn in the system level rather than a user level. I should be using `pip3 install --user mglearn` instead of `pip3 install mglearn`.

Thanks,

staronline1and2

**Comment by amueller** [comment]
Thanks for reporting back. Generally this would be considered bad behavior on the part of mglearn and I shouldn't be writing into this directory. mglearn wasn't really designed to be a real-world library, it was supposed to be a helper for the plots. I might still want to fix this.

**Comment by staronline1and2** [comment]
My apologies, I made an typo and causes confusion. 

I installed mglearn in the user level that's solved my problem. I am using pip3 install --user mglearn instead of pip3 install mglearn.
