### ISSUE TITLE
mglearn MacOsx : AttributeError: module 'enum' has no attribute 'IntFlag'

### ISSUE THREAD

**Issue by zolympe** [amueller/mglearn#17]
Hi 
The installation of mglearn work fine but when I try to import the module I have this error "AttributeError: module 'enum' has no attribute 'IntFlag'"

I tried to installl with pip3 and -user option without any improvement.
I tried to uninstall and reinstall, then to remove enum directory but importation failed.
Any Idea ?

note : Python3.7 Mac Osx Mojave

**Comment by amueller** [comment]
Hi.
Can you please provide the full traceback?
Thanks!

**Comment by zolympe** [comment]
Hi
Sorry for the delay.

I don t understand. I have just reinstall the module and now it seems to work fine

Sorry !
