### ISSUE TITLE
ImportError in `scipy.misc import image`

### ISSUE THREAD

**Issue by DrPeterVanNostrand** [amueller/mglearn#2]
## Problem:

For me (after pip installing `mglearn` and `pillow`) when running `import mglearn`, the following import error was raised:

```
ImportError Traceback (most recent call last)
in ()
4 get_ipython().magic('matplotlib inline')
5 import pandas as pd
----> 6 import mglearn
7
8 from sklearn.model_selection import train_test_split

/Users/me/programs/py3/lib/python3.5/site-packages/mglearn/init.py in ()
----> 1 from . import plots
2 from . import tools
3 from .plots import cm3, cm2
4 from .tools import discrete_scatter
5 from .plot_helpers import ReBl

/Users/me/programs/py3/lib/python3.5/site-packages/mglearn/plots.py in ()
1 from .plot_linear_svc_regularization import plot_linear_svc_regularization
----> 2 from .plot_interactive_tree import plot_tree_progressive, plot_tree_partition
3 from .plot_animal_tree import plot_animal_tree
4 from .plot_rbf_svm_parameters import plot_svm
5 from .plot_knn_regression import plot_knn_regression

/Users/me/programs/py3/lib/python3.5/site-packages/mglearn/plot_interactive_tree.py in ()
6 from sklearn.externals.six import StringIO # doctest: +SKIP
7 from sklearn.tree import export_graphviz
----> 8 from scipy.misc import imread
9 from scipy import ndimage
10 from sklearn.datasets import make_moons

ImportError: cannot import name 'imread'
```

## Fix:
I changed the following import line in the `mglearn/plot_animal_tree.py` and `mglearn/plot_interactive_tree.py` files from:

`from scipy.misc import imread` 

to 

`from scipy.misc.pilutil import imread`. 

This fixed the issue.

## Context

MacOS Jupyter notebook from a miniconda environment.

```
python==3.6.0
mglearn==0.1.3
pillow==4.0.0
scipy==0.18.1
```

**Comment by amueller** [comment]
That is odd.
Scipy 0.18.1 clearly documents ``scipy.misc.imread``: https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.misc.imread.html
Maybe open an issue there? Can you check why it's not imported into misc?

**Comment by amueller** [comment]
There's this great block in the ``scipy.misc.__init__``:
```python
try:
    from .pilutil import *
    from . import pilutil
    __all__ += pilutil.__all__
    del pilutil
except ImportError:
    pass
```
I guess that's messing with it? Yeah maybe open a scipy issue?

**Comment by DrPeterVanNostrand** [comment]
Ok, sounds good. I saw that import block too, looks kinda of crazy.

**Comment by SergioEanX** [comment]
I had the same issue and fixed it by changing the following import line in  "mglearn/plot_animal_tree.py" and "mglearn/plot_interactive_tree.py" files 
from:

`from scipy.misc import imread`

to

`from imageio import imread`

**Comment by amueller** [comment]
should be fixed now by using imageio.
