### ISSUE TITLE
Mglearn issue after the latest ubuntu update

### ISSUE THREAD

**Issue by Aiden1909** [amueller/mglearn#20]
For 2 months I have been using mglearn but since I updated to latest ubuntu release, whenever i import it shows 'No module name sklearn.externals.joblib' in the jupyter notebook. It gets fixed after reinstalling anaconda. But after shutting down the system and restarting, same error occurs
![1591791831008804846605](https://user-images.githubusercontent.com/66731551/84267251-6098b300-ab43-11ea-8739-c8c0e54ebd09.jpg)

**Comment by amueller** [comment]
please update mglearn using ``pip install -U mglearn``.

**Comment by shubhamchauhan22** [comment]
please try installing  through pip install mglearn==0.1.9
solved my issue
