### ISSUE TITLE
Readme File!!!

### ISSUE THREAD

**Issue by PurushothamanSrikanth** [amueller/mglearn#22]
@amueller First of all I would like to thank you for open-sourcing all these files under `mglearn`. 👍
Can you add Readme file and other supporting documents (with explanation) for the files under `mglearn` repo? It would be really great!!!!😁😁😁

**Comment by amueller** [comment]
Hi.
There is a readme file with installation instructions. The more elaborate documentation is in the doc folder and rendered at https://dabl.github.io

**Comment by amueller** [comment]
(sorry my previous reply was not relevant, I thought this was another repo).

This is mostly meant as helpers for the "Introduction to Machine Learning with Python" book, and so I try to keep it pretty small. Most of the functions plot different figures in the book.
I'm working on a new version of the book that doesn't rely on any additional helpers.
Is there something specific that you're interested in?

**Comment by PurushothamanSrikanth** [comment]
> (sorry my previous reply was not relevant, I thought this was another repo).
> 
> This is mostly meant as helpers for the "Introduction to Machine Learning with Python" book, and so I try to keep it pretty small. Most of the functions plot different figures in the book.
> I'm working on a new version of the book that doesn't rely on any additional helpers.
> Is there something specific that you're interested in?

Thanks!!! Im actually referring the  "Introduction to Machine Learning with Python" book and it is too good. Super excited to see your next book as well!!!!

**Comment by PurushothamanSrikanth** [comment]
Issue already resolved
