### ISSUE TITLE
Unable to install mglearn

### ISSUE THREAD

**Issue by jerrygraham** [amueller/mglearn#3]
I am trying to install mglearn in Spyder.  The pip seems to find mglearn, but it cannot be imported.  The pip I am using is as follows:  C:\Users\User\Anaconda3\Scripts\pip.exe install mglearn

This is an example of the error messages I get when I try to use it:

>>> import mglearn
>>> X,y=mglearn.datasets.load_extended_boston()
>>> print("X.shape: {}".format(X.shape))
ImportError: DLL load failed: The specified module could not be found.
>>>     __bootstrap__()
  File "C:\Users\User\Anaconda3\lib\site-packages\scipy\ndimage\_nd_image.py", line 6, in __bootstrap__
    imp.load_dynamic(__name__,__file__)
  File "C:\Users\User\Anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
    from . import plots
  File "C:\Users\User\Anaconda3\lib\site-packages\mglearn\plots.py", line 2, in <module>
    from .plot_interactive_tree import plot_tree_progressive, plot_tree_partition
  File "C:\Users\User\Anaconda3\lib\site-packages\mglearn\plot_interactive_tree.py", line 9, in <module>
    from scipy import ndimage
  File "C:\Users\User\Anaconda3\lib\site-packages\scipy\ndimage\__init__.py", line 161, in <module>
    from .filters import *
  File "C:\Users\User\Anaconda3\lib\site-packages\scipy\ndimage\filters.py", line 36, in <module>
    from . import _nd_image
  File "C:\Users\User\Anaconda3\lib\site-packages\scipy\ndimage\_nd_image.py", line 7, in <module>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User\Anaconda3\lib\site-packages\mglearn\__init__.py", line 1, in <module>

**Comment by amueller** [comment]
Is that the full error message?
That doesn't sound like an issue with mglearn, but rather with scipy.
Can you do "from scipy import ndimage" alone?
Maybe try reinstalling scipy with conda?

**Comment by omarmorales** [comment]
I cant import mglearn, got this error
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-33-26a0454c3f6e> in <module>()
----> 1 import mglearn

ModuleNotFoundError: No module named 'mglearn'

**Comment by amueller** [comment]
@omarmorales how did you install mglearn?

**Comment by amueller** [comment]
closing as no reply. Feel free to reopen.

**Comment by TimdePooter** [comment]
Dear Andreas,

I've installed mglearn in the anaconda terminal using pip install mglearn. When I try to create the forge dataset using X, y = mglearn.datasets.make_forge()  I get the error message : NameError: name 'mglearn' is not defined. I'm working in Spyder, not Jupyter notebook...

Is there anything I'm missing here? Sorry to bother you with this, as I see that you already got many requests over installing mglearn, but I have trouble tackling it...

Thank you.

**Comment by amueller** [comment]
@TimdePooter did you do ``import mglearn``?

**Comment by TimdePooter** [comment]
@amueller , indeed I seem to have forgotten to do that. Stupid of me... Thank you for your time.

**Comment by ruicosta1988** [comment]
I can not import mglearn as well.
After I installed mglearn, I checked the version.  Version is 0.1.6.
When I import mglearn on jupyter notebook, the following message is appeared.
ModuleNotFoundError: No module named 'mglearn'
How can I fix?

**Comment by amueller** [comment]
@ruicosta1988 you probably didn't install it in the environment your jupyter notebook is using, see https://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/

**Comment by ruicosta1988** [comment]
Sorry for my late reply. I could install and import it.  Thank you

**Comment by amueller** [comment]
@ruicosta1988 glad you could figure it out

**Comment by ritvikkashyap** [comment]
unable to install mgleran using '' pip install mglearn'' in vscode 
![capture jpg11](https://user-images.githubusercontent.com/45793401/50338434-49729980-053a-11e9-9f11-391ec3c20576.JPG)

**Comment by amueller** [comment]
@ritvikkashyap either you didn't have internet when you tried it or pypi was down. Try again now.

**Comment by ritvikkashyap** [comment]
@amueller : regarding internet- I have high speed internet access. So there is no issue with that.
                    Regarding pypi was down: how come every time that is happening. I have tried many times. (Other libraries are getting downloaded except mglearn.)

**Comment by amueller** [comment]
That's odd. With that error message? This says server timeout, right?

**Comment by ritvikkashyap** [comment]
yeah true. That's the reason i am not able to understand what's the problem

**Comment by slowwindsawan** [comment]
Hii dear. I also faced the same problem and I hope that the solution what I
used can help you too.

Either your python pip version does not match your Python VM. So, try to
update to the latest version or try installing mglearn manually.

**Comment by ritvikkashyap** [comment]
Thanku for the suggestion .I will surely try that out but can you please
tell me how can i install mglearn manually?
