### ISSUE TITLE
 display(graphviz.Source('dot_graph')) issues

### ISSUE THREAD

**Issue by jjbaek35** [amueller/mglearn#7]
I faced errors with running follows example in the book:
*******************************************
import graphviz
from IPython.display import display
with open("tree.dot") as f:
    dot_graph = f.read()
    display(graphviz.Source('dot_graph'))
*********************************************

FileNotFoundError                         Traceback (most recent call last)
e:\Users\users\AppData\Local\Continuum\anaconda3\lib\site-packages\graphviz\backend.py in pipe(engine, format, data, quiet)
    158             stdout=subprocess.PIPE, stderr=subprocess.PIPE,
--> 159             **POPEN_KWARGS)
    160     except OSError as e:

e:\Users\users\AppData\Local\Continuum\anaconda3\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors)
    708                                 errread, errwrite,
--> 709                                 restore_signals, start_new_session)
    710         except:

e:\Users\users\AppData\Local\Continuum\anaconda3\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
    996                                          os.fspath(cwd) if cwd is not None else None,
--> 997                                          startupinfo)
    998             finally:

FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

ExecutableNotFound                        Traceback (most recent call last)
e:\Users\users\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\formatters.py in __call__(self, obj)
    343             method = get_real_method(obj, self.print_method)
    344             if method is not None:
--> 345                 return method()
    346             return None
    347         else:

e:\Users\users\AppData\Local\Continuum\anaconda3\lib\site-packages\graphviz\files.py in _repr_svg_(self)
    104 
    105     def _repr_svg_(self):
--> 106         return self.pipe(format='svg').decode(self._encoding)
    107 
    108     def pipe(self, format=None):

e:\Users\users\AppData\Local\Continuum\anaconda3\lib\site-packages\graphviz\files.py in pipe(self, format)
    123         data = text_type(self.source).encode(self._encoding)
    124 
--> 125         outs = backend.pipe(self._engine, format, data)
    126 
    127         return outs

e:\Users\users\AppData\Local\Continuum\anaconda3\lib\site-packages\graphviz\backend.py in pipe(engine, format, data, quiet)
    160     except OSError as e:
    161         if e.errno == errno.ENOENT:
--> 162             raise ExecutableNotFound(args)
    163         else:  # pragma: no cover
    164             raise

ExecutableNotFound: failed to execute ['dot', '-Tsvg'], make sure the Graphviz executables are on your systems' PATH

<graphviz.files.Source at 0x1d8a7f6d208>

*****************************
** my versions:
Python version: 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]
pandas version: 0.23.0
matplotlib version: 2.2.2
NumPy version: 1.13.3
SciPy version: 1.1.0
IPython version: 6.4.0
scikit-learn version: 0.19.1
graphviz version: 0.8.4

**Comment by amueller** [comment]
you need to ``conda install graphviz``.

**Comment by jjbaek35** [comment]
I tried to install it, but it occurs another error:
******************************************************
(base) C:\Users\users>conda install graphviz
Solving environment: done

## Package Plan ##

  environment location: C:\Users\users\AppData\Local\Continuum\anaconda3

  added / updated specs:
    - graphviz


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    graphviz-2.38.0            |                4        37.7 MB

The following NEW packages will be INSTALLED:

    graphviz: 2.38.0-4

Proceed ([y]/n)? y


Downloading and Extracting Packages
graphviz-2.38.0      | 37.7 MB | ############################################################################## | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(base) C:\Users\users>python
Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
->>> import graphviz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'graphviz'
->>>

**Comment by jjbaek35** [comment]
I solved with following additional command

conda install python-graphviz

Thanks.
